import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="top-bar">
          <Link href={"/"}>home</Link>
          <Link href={"/page1"}>page1</Link>
          <Link href={"/page2"}>page2</Link>
          <Link href={"/table"}>table</Link>
        </div>
        <div style={{
          padding: "4em",

        }}>
          <p style={{
            fontSize: '20px',
            marginBottom: '2em',
          }}>Navigate Between the pages, home then page 1 then page 2 (good so far) - then go to table and back to page 2 (will be slow - very.. slow)</p>

          <div>
            
          {children}
          </div>
          </div>
      </body>
    </html>
  );
}
